const words = [
  { english: "executive", meaning: "경영진" },
  { english: "inventory", meaning: "재고" },
  { english: "feature", meaning: "특징" },
  { english: "acknowledge", meaning: "인정하다" },
  { english: "voucher", meaning: "상품권" },
  { english: "estimate", meaning: "견적서" },
  { english: "resume", meaning: "이력서" },
  { english: "issue", meaning: "문제" },
  { english: "property", meaning: "재산" },
  { english: "eligible", meaning: "자격이 있는" },
  { english: "initiative", meaning: "주도권" },
  { english: "culinary", meaning: "요리의" },
  { english: "extensive", meaning: "광범위한" },
  { english: "deposit", meaning: "보증금" },
  { english: "retail", meaning: "소매" },
  { english: "affordable", meaning: "가격이 알맞은" },
  { english: "grant", meaning: "승인하다" },
  { english: "significantly", meaning: "상당히" },
  { english: "reserve", meaning: "예약하다" },
  { english: "application", meaning: "신청서" },
  { english: "address", meaning: "주소" },
  { english: "suppose", meaning: "추정하다" },
  { english: "charge", meaning: "요금" },
  { english: "expire", meaning: "만료되다" },
  { english: "refund", meaning: "환불" },
  { english: "promote", meaning: "촉진하다" },
  { english: "revenue", meaning: "수익" },
  { english: "opportunity", meaning: "기회" },
  { english: "valid", meaning: "유효한" },
  { english: "confidential", meaning: "기밀의" },
  { english: "figure", meaning: "숫자" },
  { english: "traffic", meaning: "교통" },
  { english: "audience", meaning: "청중" },
  { english: "occupy", meaning: "차지하다" },
  { english: "approximately", meaning: "대략" },
  { english: "complimentary", meaning: "무료의" },
  { english: "outstanding", meaning: "미해결의" },
  { english: "imperative", meaning: "긴급한" },
  { english: "substantial", meaning: "상당한" },
  { english: "decline", meaning: "감소하다" },
  { english: "balance", meaning: "균형" },
  { english: "account", meaning: "계좌" },
  { english: "proceed", meaning: "진행하다" },
  { english: "amenities", meaning: "편의시설" },
  { english: "renowned", meaning: "유명한" },
  { english: "preserve", meaning: "보존하다" },
  { english: "simply", meaning: "단순하게" },
  { english: "presence", meaning: "존재" },
  { english: "laboratory", meaning: "실험실" },
  { english: "effective", meaning: "효과적인" },
  { english: "enhance", meaning: "향상시키다" },
  { english: "insurance", meaning: "보험" },
  { english: "spacious", meaning: "넓은" },
  { english: "ingredient", meaning: "재료" },
  { english: "withdraw", meaning: "철회하다" },
  { english: "banquet", meaning: "연회" },
  { english: "experiment", meaning: "실험" },
  { english: "specific", meaning: "구체적인" },
  { english: "specialize", meaning: "전문화하다" },
  { english: "affect", meaning: "영향을 미치다" },
  { english: "equip", meaning: "장비를 제공하다" },
  { english: "reimbursement", meaning: "환급" },
  { english: "premises", meaning: "부지" },
  { english: "renovate", meaning: "개조하다" },
  { english: "versatile", meaning: "다재다능한" },
  { english: "implement", meaning: "실행하다" },
  { english: "informed", meaning: "정보에 기반한" },
  { english: "commitment", meaning: "약속" },
  { english: "direct", meaning: "직접적인" },
  { english: "facilitate", meaning: "용이하게 하다" },
  { english: "commission", meaning: "수수료" },
  { english: "cover", meaning: "덮다" },
  { english: "encourage", meaning: "격려하다" },
  { english: "persuade", meaning: "설득하다" },
  { english: "accompany", meaning: "동반하다" },
  { english: "candidate", meaning: "후보자" },
  { english: "renew", meaning: "갱신하다" },
  { english: "launch", meaning: "출시하다" },
  { english: "reliable", meaning: "믿을 수 있는" },
  { english: "inform", meaning: "알리다" },
  { english: "contribute", meaning: "기여하다" },
  { english: "strategy", meaning: "전략" },
  { english: "motivate", meaning: "동기부여하다" },
  { english: "consider", meaning: "고려하다" },
  { english: "remind", meaning: "상기시키다" },
  { english: "suitable", meaning: "적합한" },
  { english: "beverage", meaning: "음료" },
  { english: "portable", meaning: "휴대할 수 있는" },
  { english: "essential", meaning: "필수적인" },
  { english: "consent", meaning: "동의" },
  { english: "tentative", meaning: "잠정적인" },
  { english: "respective", meaning: "각각의" },
  { english: "arrange", meaning: "정리하다" },
  { english: "associate", meaning: "관련시키다" },
  { english: "publicity", meaning: "홍보" },
  { english: "instructor", meaning: "강사" },
  { english: "contractor", meaning: "계약자" },
  { english: "relevant", meaning: "관련 있는" },
  { english: "weekly", meaning: "매주 열리는" },
  { english: "imply", meaning: "암시하다" }
];
